# Generated by Django 5.0.6 on 2024-06-11 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0002_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('P', 'Passage'), ('Q', 'Question'), ('G', 'Game')], default='P', max_length=1)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='passages.story')),
            ],
        ),
    ]
