# Generated by Django 5.0.6 on 2024-06-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0003_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_number',
            field=models.IntegerField(default=1),
        ),
    ]
