# Generated by Django 5.0.6 on 2024-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0005_verse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField()),
            ],
        ),
    ]
