# Generated by Django 5.0.6 on 2024-09-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0006_personalisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteVerses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
            ],
        ),
    ]
