# Generated by Django 5.0.6 on 2024-09-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0007_favouriteverses'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouriteverses',
            name='user_sub',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='personalisation',
            name='current_story',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='personalisation',
            name='user_sub',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='personalisation',
            name='current_step',
            field=models.IntegerField(default=0),
        ),
    ]
