# Generated by Django 5.0.6 on 2024-09-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0008_favouriteverses_user_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteMaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sub', models.CharField(default='', max_length=100)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sub', models.CharField(default='', max_length=100)),
                ('story_name', models.CharField(default='', max_length=50)),
                ('step_number', models.IntegerField()),
            ],
        ),
    ]
