# Generated by Django 5.0.6 on 2024-09-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passages', '0009_favouritemaps_favouritestep'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastStoryline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sub', models.CharField(default='', max_length=100)),
                ('story_name', models.CharField(max_length=50)),
            ],
        ),
    ]
